title: freeRADIUS-Google-StepCA
description: Set up 802.1X using Step CA as PKI, freeRADIUS and Google as IdP
theme: just-the-docs

#color_scheme: dark

url: https://matteoraf.github.io/freeRADIUS-Google-StepCA

# For copy button on code
enable_copy_code_button: true

back_to_top: true
back_to_top_text: "Back to top"

callouts_level: quiet # or loud
callouts:
  highlight:
    color: yellow
  important:
    title: Important
    color: blue
  new:
    title: New
    color: green
  note:
    title: Note
    color: purple
  warning:
    title: Warning
    color: red
  disclaimer:
    title: Disclaimer
    color: yellow
  ref:
    title: Ref
    color: grey-lt